/**
 * Created By: petar.danadzhiev@next-consult.com - Junior Developer.
 * Created Date: 25.6.2024 г..
 *
 * @description Apex Class representing the elements in "CommonAggregateComponents" also known as C.A.C from "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
 */
public class CAC {
	private static final String CAC_NAMESPACE = 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2';

	public class AccountingSupplierParty implements XmlNodeCustom {

		public AccountingSupplierParty(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class AccountingCustomerParty implements XmlNodeCustom {

		public AccountingCustomerParty(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class Country implements XmlNodeCustom {

		public Country(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class ClassifiedTaxCategory implements XmlNodeCustom {

		public ClassifiedTaxCategory(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class LegalMonetaryTotal implements XmlNodeCustom {

		public LegalMonetaryTotal(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class InvoiceLine implements XmlNodeCustom {

		public InvoiceLine(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class Item implements XmlNodeCustom {

		public Item(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class Price implements XmlNodeCustom {

		public Price(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class Party implements XmlNodeCustom {

		public Party(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class PostalAddress implements XmlNodeCustom {

		public PostalAddress(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class PartyName implements XmlNodeCustom {

		public PartyName(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class PartyLegalEntity implements XmlNodeCustom {

		public PartyLegalEntity(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class PaymentMeans implements XmlNodeCustom {

		public PaymentMeans(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class TaxTotal implements XmlNodeCustom {

		public TaxTotal(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class TaxSubtotal implements XmlNodeCustom {

		public TaxSubtotal(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class TaxCategory implements XmlNodeCustom {

		public TaxCategory(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}

	public class TaxScheme implements XmlNodeCustom {

		public TaxScheme(){}

		public void populateXmlNode(Dom.XmlNode outerNode){

		}
	}
}